name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@V3
        with:
          python-version: '3.12'
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          pipenv install --dev
          playwright install
      - name: Run Tests
        run: pytest -v